service: image-resize-on-the-fly-bucket

custom:
  secrets: ${file(../secrets/secrets.json)} # will be created in our deploy.sh script

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${env:STAGE, 'dev'}
  profile: ${env:SLS_PROFILE}
  region: ${env:REGION}
  environment:
    BUCKET: ${env:BUCKET}

resources:
  Resources:
    GIResized:
      Type: AWS::S3::Bucket # creating an S3 Bucket
      Properties:
        AccessControl: PublicReadWrite
        BucketName: ${env:BUCKET}
        WebsiteConfiguration: # enabling the static website option
          ErrorDocument: error.html
          IndexDocument: index.html
          RoutingRules: # telling it to redirect for every 404 error
            - RedirectRule:
                HostName: ${self:custom.secrets.DOMAIN} # API Gateway domain
                HttpRedirectCode: "307" # temporary redirect HTTP code
                Protocol: "https"
                ReplaceKeyPrefixWith: "${self:provider.stage}/resize?key=" # route
              RoutingRuleCondition:
                HttpErrorCodeReturnedEquals: "404"
                KeyPrefixEquals: ""
    GIResizedPolicy:
      Type: AWS::S3::BucketPolicy # add policy for public read access
      Properties:
        Bucket:
          Ref: GIResized
        PolicyDocument:
          Statement:
            - Action:
                - "s3:*"
              Effect: "Allow"
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: GIResized
                    - "/*"
              Principal: "*"